# Generated by Django 3.1.2 on 2020-10-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constrprojmodel',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='construction_project/img'),
        ),
    ]
